package com.jsp.lostAndFound.entity;

public enum NotificationType {

    RECOVERY_REQUEST_CREATED,
    RECOVERY_REQUEST_ACCEPTED,
    ITEM_RETURNED,
    RECOVERY_COMPLETED,
    COMPLAINT_RESOLVED,
    COMPLAINT_REJECTED
}